version: "3"

services:
  cert_gen:
      container_name: "cert-gen"
      image: paulczar/omgwtfssl
      volumes:
      - certs:/certs
      labels:
        - "traefik.enable=false"

  traefik:
      build: traefik/
      container_name: "traefik"
      networks:
        - default
        - inside
      ports:
      - 80:80
      - 443:443
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/certs
      - logs:/logs
      labels:
      - "traefik.frontend.rule=PathPrefixStrip:/api"
      - "traefik.frontend.auth.basic.usersFile=/etc/traefik/.htpasswd"
      - "traefik.port=8081"


        

  templates:
      build : templates/
      container_name: "templates"
      networks: 
        - inside
      labels:
        - "traefik.enable=false"

  public-files:
      image: aikain/simplehttpserver:0.1
      container_name: "public-files"
      volumes:
        - files:/var/www/
        - logs:/var/www/logs
      networks:
        - inside
      labels:
        - "traefik.sec.frontend.rule=PathPrefixStrip:/files/logs"
        - "traefik.sec.port=80"
        - "traefik.sec.frontend.auth.basic.users=admin:$$apr1$$JWufnu2u$$jK16K8EczmfIBDk5p3xw6/"
        - "traefik.nosec.frontend.rule=PathPrefixStrip:/files"
        - "traefik.nosec.port=80"
  
  
  portainer:
      image: portainer/portainer-ce
      container_name: "portainer-app"
      networks:
        - inside
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/portainer/data:/data
      command:  --host=unix:///var/run/docker.sock --logo "https://i.imgur.com/kfi99Po.png" --templates "http://templates/templates.json"

      labels:
        - "traefik.frontend.rule=PathPrefixStrip:/portainer"
        - "traefik.port=9000"
        - "traefik.passHostHeader=true"
        - "traefik.docker.network=redcloud_inside"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=drr"
        # https://github.com/containous/traefik/issues/563#issuecomment-421360934
        - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
        - "traefik.frontend.redirect.replacement=$$1/portainer/"
        - "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"

volumes:
  certs:
  logs:
  files:
networks:
  inside:
    external: false
